### ISSUE TITLE
建议并入现有pf2中文化项目

### ISSUE THREAD

**Issue by bnp800** [AlphaStarguide/PF2E_compendium_cn#4]
https://github.com/fvtt-cn/pf2_cn

为避免重复劳动，建议并入现有pf2中文化项目。

感谢你们的辛勤劳动

**Comment by AlphaStarguide** [comment]
跟PF2中文化项目人员沟通后，达成集合包的汉化应独立一个mod的共识
鉴于PF2中文化项目已有一些集合包的汉化内容（主要是法术和装备），这部分的代码应如何处理之后我再跟他讨论一下
